### ISSUE TITLE
Error after last epoch

### ISSUE THREAD

**Issue by jHaselberger** [eyalzk/dlbot#1]
Hi first of all: your project is great! Really helpful in daily use.

One thing I noticed:  After the last epoch this error is thrown:
`Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "C:\Users\Johann.Haselberger\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\_pylab_helpers.py", line 78, in destroy_all
    manager.destroy()
  File "C:\Users\Johann.Haselberger\AppData\Local\Programs\Python\Python36\lib\site-packages\matplotlib\backends\_backend_tk.py", line 558, in destroy
    self.window.destroy()
  File "C:\Users\Johann.Haselberger\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 2058, in destroy
    for c in list(self.children.values()): c.destroy()
  File "C:\Users\Johann.Haselberger\AppData\Local\Programs\Python\Python36\lib\tkinter\__init__.py", line 2302, in destroy
    self.tk.call('destroy', self._w)
RuntimeError: main thread is not in main loop`

**Comment by eyalzk** [comment]
Hi @gismo07 , thanks!
Can you please specify on which example did this error occur?
Also, which version of Tensorflow / Keras are you using?
